add_newline = false
scan_timeout = 500

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[git_branch]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[docker_context]
symbol = " "
